### ISSUE TITLE
Regarding memory exhaustion with BRCG

### ISSUE THREAD

**Issue by Shivampanwar** [Trusted-AI/AIX360#94]
I am trying BRCG on my dataset. I have nearly 40 features but most of them are categorical. I have nearly 18k rows or examples of labeled data. After feature binarization, my dataset gets converted into 35 thousand features and now my overall dimension of data is (18K,35k).  Now, I run BRCG on this, but it throws memory error as shown below. 
![image](https://user-images.githubusercontent.com/12275601/86084426-84a04200-baba-11ea-9454-663747de1743.png)
The issue might be due to memory allocation in cvxpy module. Any help in resolving this issue will be highly appreciated. I am using 32GB RAM.

**Comment by dennislwei** [comment]
Your categorical features must have a lot of categories to result in 35k features after binarization.

I recommend that you look at FeatureBinarizerFromTrees (PR #77, thanks to @floidgilbert) and the [notebook](https://github.com/IBM/AIX360/blob/master/examples/rbm/feature_binarizer_from_trees.ipynb) illustrating its usage. Instead of creating binary features for all possible categories like FeatureBinarizer, it generates them based on splits in fitted decision trees. This should result in a much smaller number of relevant features.
